### ISSUE TITLE
npm outdated detection with beta

### ISSUE THREAD

**Issue by computeronix** [storj/storj-automation#58]
if you use the beta branch the current outdated method that checks to see if you have the latest version returns incorrect values causing the script to attempt to install storjshare-cli everytime causing extra delay and potential downtime for other nodes on the same machine

**Comment by computeronix** [comment]
will test outdated with storjshare-cli@next when next beta branch update is released and then can modify the code from there

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
